site_name: My dev assets


theme:
  name: material
  palette:
    scheme: default   # or slate for dark mode
  features:
    - navigation.expand      # ‚Üê THIS IS THE KEY
    - navigation.sections    # treats top-level sections as expandable (optional but nice)
    - navigation.indexes     # allows index pages in sections
    - toc.integrate          # merges table of contents into sidebar (optional, looks more like RTD)
  icon:
    logo: material/library

plugins:
  - search
  - asciinema-player

markdown_extensions:
  - callouts
  - mkdocs_graphviz

extra_javascript:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js
